package pokeapi

import (
	"encoding/json"
	"io"
	"net/http"
)


type AutoGenerated struct {
	ConditionValues []struct {
		Name string `json:"name"`
		URL  string `json:"url"`
	} `json:"condition_values"`
}
type PokemonsInLocationResponse struct {
	EncounterMethodRates []struct {
		EncounterMethod struct {
			Name string `json:"name"`
			URL  string `json:"url"`
		} `json:"encounter_method"`
		VersionDetails []struct {
			Rate    int `json:"rate"`
			Version struct {
				Name string `json:"name"`
				URL  string `json:"url"`
			} `json:"version"`
		} `json:"version_details"`
	} `json:"encounter_method_rates"`
	GameIndex int `json:"game_index"`
	ID        int `json:"id"`
	Location  struct {
		Name string `json:"name"`
		URL  string `json:"url"`
	} `json:"location"`
	Name  string `json:"name"`
	Names []struct {
		Language struct {
			Name string `json:"name"`
			URL  string `json:"url"`
		} `json:"language"`
		Name string `json:"name"`
	} `json:"names"`
	PokemonEncounters []struct {
		Pokemon struct {
			Name string `json:"name"`
			URL  string `json:"url"`
		} `json:"pokemon"`
		VersionDetails []struct {
			EncounterDetails []struct {
				Chance          int   `json:"chance"`
				ConditionValues []struct {
					Name string `json:"name"`
					URL  string `json:"url"`
				} `json:"condition_values"`
				MaxLevel        int   `json:"max_level"`
				Method          struct {
					Name string `json:"name"`
					URL  string `json:"url"`
				} `json:"method"`
				MinLevel int `json:"min_level"`
			} `json:"encounter_details"`
			MaxChance int `json:"max_chance"`
			Version   struct {
				Name string `json:"name"`
				URL  string `json:"url"`
			} `json:"version"`
		} `json:"version_details"`
	} `json:"pokemon_encounters"`
}

func (c *Client) ListPokemonsInLocation(locationName string) (PokemonsInLocationResponse, error) {
	url := baseUrl + locationAreaPath + "/" + locationName

	if cachedData, exists := c.cache.Get(url); exists {
		pokemonInLocationData := PokemonsInLocationResponse{}
		err := json.Unmarshal(cachedData, &pokemonInLocationData)
		if err != nil {
			return PokemonsInLocationResponse{}, err
		}

		return pokemonInLocationData, nil
	}

	req, err := http.NewRequest("GET", url, nil)
	if err != nil {
		return PokemonsInLocationResponse{}, err
	}

	resp, err := c.httpClient.Do(req)
	if err != nil {
		return PokemonsInLocationResponse{}, err
	}
	defer resp.Body.Close()

	data, err := io.ReadAll(resp.Body)
	if err != nil {
		return PokemonsInLocationResponse{}, err
	}

	c.cache.Add(url, data)

	pokemonInLocationData := PokemonsInLocationResponse{}
	err = json.Unmarshal(data, &pokemonInLocationData)
	if err != nil {
		return PokemonsInLocationResponse{}, err
	}

	return pokemonInLocationData, nil

}